stages:
- stage: firstruntar
  displayName: 'Empty cache TAR'
  variables:
    CACHE_PACK: tar
  jobs:
  - template: azure-pipelines-jobs.yml

- stage: firstrunfiles
  displayName: 'Empty Cache Files'
  variables:
    AZP_CACHING_CONTENT_FORMAT: Files
    CACHE_PACK: files
  jobs:
  - template: azure-pipelines-jobs.yml

- stage: secondruntar
  dependsOn: firstruntar
  displayName: 'Cached Tar'
  variables:
    CACHE_PACK: tar
  jobs:
  - template: azure-pipelines-jobs.yml

- stage: secondrunfiles
  dependsOn: firstrunfiles
  displayName: 'Cached Files'
  variables:
    AZP_CACHING_CONTENT_FORMAT: Files
    CACHE_PACK: files
  jobs:
  - template: azure-pipelines-jobs.yml

variables:
  GRADLE_USER_HOME: $(Pipeline.Workspace)/.gradle
  CACHE_KEY: gradle | $(Agent.OS) | $(Build.BuildId) | $(CACHE_PACK) | gradle.properties
  CACHE_RESTOREKEY: gradle | $(Agent.OS) | $(Build.BuildId)
  system.debug: true

#jobs:
#- job: linux_11
#  displayName: Linux (OpenJDK 11)
#  pool:
#    vmImage: 'ubuntu-16.04'
#  steps:
#    - checkout: self
#      fetchDepth: 10
#    - template: src/azure/azure-gradle-step.yml
#      parameters:
#        publishTestResults: true
#
#- job: linux_12
#  displayName: Linux (OpenJDK 12)
#  pool:
#    vmImage: 'ubuntu-16.04'
#  container: openjdk:12
#  steps:
#    - checkout: self
#      fetchDepth: 10
#    - template: src/azure/azure-gradle-step.yml
#
#- job: linux_13
#  displayName: Linux (OpenJDK 13)
#  pool:
#    vmImage: 'ubuntu-16.04'
#  container: openjdk:13
#  steps:
#    - checkout: self
#      fetchDepth: 10
#    - template: src/azure/azure-gradle-step.yml
#      parameters:
#        continueOnError: true
#
#- job: Mac
#  pool:
#    vmImage: 'macOS-10.13'
#  steps:
#    - checkout: self
#      fetchDepth: 10
#    - template: src/azure/azure-gradle-step.yml
#
#- job: Windows
#  pool:
#    vmImage: 'windows-2019'
#  steps:
#    - checkout: self
#      fetchDepth: 10
#    - template: src/azure/azure-gradle-step.yml

